apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-slack-app
  labels: 
    app: flask-slack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-slack-app
  template:
    metadata:
      labels:
        app: flask-slack-app
    spec:
      restartPolicy: Always
      containers:
      - name: flask-slack-app
        image: adube2/flask-slack-app
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080
        env:
          - name: FLASK_ENV
            value: "production"
      # imagePullSecrets:
      # - name: secret/my-docker-hub-secret
---

apiVersion: v1
kind: Service
metadata:
  name: flask-slack-app-service
spec:
  selector:
    app: flask-slack-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      nodePort: 30000  # Specify a custom NodePort
  type: NodePort