import os


class Config(object):
    """
    Configuration class for setting up environment-specific application settings, including database
    and Slack API credentials.

    **Why**: Centralizes configuration variables, making it easy to manage environment-specific settings
    like database connections and Slack integration securely through environment variables.

    **How**: Common usage examples:
    1. `Config.SQLALCHEMY_DATABASE_URI`: Access the database URI for connecting to the application’s database.
    2. `Config.SLACK_BOT_TOKEN`: Access the Slack bot token used for authenticating with the Slack API.
    """

    SQLALCHEMY_TRACK_MODIFICATIONS = False
    """
    Disable SQLAlchemy track modifications to reduce overhead.

    **Why**: Prevents SQLAlchemy from tracking every modification to objects, improving performance.
    """

    SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE_URL")
    """
    Database URI for SQLAlchemy connection, sourced from the `DATABASE_URL` environment variable.

    **Why**: Stores the URI needed to connect to the database, essential for database interactions.
    **How**: Automatically set from environment variables to allow different configurations in different environments.
    """

    SQLALCHEMY_ECHO = True
    """
    Enable SQLAlchemy echo mode to log SQL statements generated by the ORM.

    **Why**: Useful for debugging by showing the exact SQL commands being executed.
    """

    SLACK_SIGNING_SECRET = os.environ.get("SLACK_SIGNING_SECRET")
    """
    Slack signing secret used for verifying request authenticity.

    **Why**: Ensures requests are genuinely from Slack by verifying them using this secret.
    **How**: Retrieved from environment variables for security, avoiding hard-coding sensitive data.
    """

    SLACK_BOT_TOKEN = os.environ.get("SLACK_BOT_TOKEN")
    """
    Slack bot token for authorizing API requests made by the bot.

    **Why**: Enables the application to authenticate and interact with Slack’s API on behalf of the bot.
    **How**: Set as an environment variable to maintain security and flexibility across environments.
    """

    VERIFICATION_TOKEN = os.environ.get("VERIFICATION_TOKEN")
    """
    Verification token for additional Slack request verification.

    **Why**: Adds another layer of security to verify requests if needed by Slack’s API.
    **How**: Retrieved from environment variables to keep sensitive information secure.
    """
