name: CI/CD Pipeline with Minikube and Docker Hub

on:
  push:
    branches:
      - dubeavik
  pull_request:
    branches:
      - dubeavik

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      # Step 3: Install Minikube
      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          sudo apt-get install -y conntrack # Required for Minikube

      # Step 4: Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Step 2: Start Minikube
      - name: Start Minikube
        run: |
          sudo minikube start --driver=none
          sudo minikube status

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push Docker Image
        run: |
          eval $(sudo minikube docker-env)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-slack-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-slack-app

      # Step 5: Pull Docker Image into Minikube
      - name: Pull Docker Image into Minikube
        run: |
          eval $(sudo minikube docker-env)
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-slack-app
          docker tag ${{ secrets.DOCKER_USERNAME }}/flask-slack-app 

      # Step 6: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml

      # Step 7: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get pods
