name: CI/CD Pipeline with Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python (required for testing with pytest)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-slack-app .

      # Step 6: Docker login to Docker Hub (using GitHub secrets)
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Step 7: Push Docker image to Docker Hub
      - name: Check Docker Images
        run: docker images
      # Step 7: Push Docker image to Docker Hub
      - name: Push Docker Images
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-slack-app:latest
      - name: Set up Minikube
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin

      # Step 8: Start Minikube
      - name: Start Minikube
        run: |
          minikube start --driver=docker

      # Step 9: Set up kubectl to use the Minikube cluster
      - name: Set up kubectl
        run: |
          kubectl config use-context minikube

      # Step 10: Apply the Kubernetes manifest to the Minikube cluster
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml
          kubectl get pods

      # Step 11: Deploy to Kubernetes (you should have your k8s/deployment.yaml configured)
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml
