name: CI/CD Pipeline with Minikube and Docker Hub

on:
  push:
    branches:
      - dubeavik
  pull_request:
    branches:
      - dubeavik

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install dependencies (Minikube, kubectl, and Docker)
      - name: Install Minikube and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https curl
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          sudo apt-get install -y docker.io

      # Step 2: Start Minikube
      - name: Start Minikube
        run: |
          sudo minikube start --driver=none
          sudo minikube status

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and Push Docker Image to Docker Hub
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-slack-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-slack-app

      # Step 5: Pull Docker Image into Minikube
      - name: Pull Docker Image into Minikube
        run: |
          eval $(sudo minikube docker-env)
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-slack-app
          docker tag ${{ secrets.DOCKER_USERNAME }}/flask-slack-app 

      # Step 6: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml

      # Step 7: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get pods
